### ISSUE TITLE
关于参数的问题

### ISSUE THREAD

**Issue by yglb** [HeiShanLaoYao889/super-tcplayer#2]
option:{
    fileID:"sdasads2e21",
    appID:"asdasda",
    us:'',
    t:'',
    sign:'',exper:''
}

这几个参数, 都代表这个什么啊, fileID和appID我查了一下, 大概知道是什么, 但是剩下两个又是什么, 播放的url路径又要放到哪里

**Comment by yglb** [comment]
@HeiShanLaoYao889

**Comment by DavisYao88** [comment]
这个是基于fileID播放视频的,指定使用腾讯云点播管理才可以.至于url是在播放器SDK内部实现的 hsl流文件播放.

**Comment by yglb** [comment]
> 这个是基于fileID播放视频的,指定使用腾讯云点播管理才可以.至于url是在播放器SDK内部实现的 hsl流文件播放.

那我要如何才能告知TCPlayer我的播放路径呢, 我找半天, 不知道应该把这个路径放在哪里

**Comment by DavisYao88** [comment]
不需要视频URL 如果你们公司开通课腾讯云点播业务  初始化播放器传入视频的fileID即可播放

**Comment by yglb** [comment]
> 不需要视频URL 如果你们公司开通课腾讯云点播业务 初始化播放器传入视频的fileID即可播放

这个....情况似乎与我们的实际情况有点出入啊, 因为是直播系统, 所以, 这个地址是有好几个的, 如果我不写明, 那不就...乱了吗?

**Comment by DavisYao88** [comment]
针对直播还有另外的组件,没有一起打包

**Comment by yglb** [comment]
> 针对直播还有另外的组件,没有一起打包

额, 你方便给我一下不
